/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    {type: 'doc', id: 'README', label: 'Overview'},
    'docs/installation',
    'docs/commands',
    'docs/sync-states',
    {type: 'category', label: 'Walkthrough', items: [{type: 'autogenerated', dirName: 'test/walkthrough'}]},
    {type: 'category', label: 'Comparisons', items: [{type: 'autogenerated', dirName: 'test/comparisons'}]},
    {type: 'category', label: 'Design', items: [{type: 'autogenerated', dirName: 'docs/design'}]},
    {type: 'doc', id: 'test/concepts/sync-model/README', label: 'Sync model'},
    {type: 'doc', id: 'test/concepts/upstreams/README', label: 'Upstreams'},
    {type: 'doc', id: 'test/concepts/splice-identity/README', label: 'Splice identity'},
    {
      type: 'category',
      label: 'Nesting',
      link: {type: 'doc', id: 'test/concepts/nesting/README'},
      items: ['test/concepts/nesting/diamond', 'test/concepts/nesting/cycle'],
    },
    {type: 'category', label: 'Going forward', items: [{type: 'autogenerated', dirName: 'docs/going-forward'}]},
    {type: 'category', label: 'Scenarios', items: [{type: 'autogenerated', dirName: 'test/scenarios'}]},
    'docs/development',
    'CONTRIBUTING',
  ],
};
