/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    {type: 'doc', id: 'README', label: 'Overview'},
    'docs/installation',
    'docs/commands',
    'docs/sync-states',
    {type: 'category', label: 'Walkthrough', items: [{type: 'autogenerated', dirName: 'test/walkthrough'}]},
    {type: 'category', label: 'Comparisons', items: [{type: 'autogenerated', dirName: 'test/comparisons'}]},
    {type: 'category', label: 'Design', items: [{type: 'autogenerated', dirName: 'docs/design'}]},
    {type: 'category', label: 'Scenarios', items: [{type: 'autogenerated', dirName: 'test/scenarios'}]},
    'docs/development',
    'CONTRIBUTING',
  ],
};
